/*
 * OLEDNEW.h
 *
 *  Created on: 19 Eki 2019
 *      Author: Orhan
 */

#ifndef INC_OLEDNEW_H_
#define INC_OLEDNEW_H_



#include <fonts.h>
#include "stm32f1xx_hal.h"

#define OLED_Display_On							0xAF
#define OLED_Display_Off						0xAE
#define OLED_Constrast_Set						0x81
#define OLED_Display_All_On_Resume				0xA4
#define OLED_Display_All_On						0xA5
#define OLED_Display_Normal						0xA6
#define OLED_Display_Inverse					0xA7

//Scrolling Command Table
#define OLED_Scroll_Activate					0x2F
#define OLED_Scroll_Deactivate					0x2E
#define OLED_Scroll_Left						0x27
#define OLED_Scroll_Right						0x26
#define OLED_Scroll_Vertical_Left				0x2A
#define OLED_Scroll_Vertical_Right				0x29
#define OLED_Scroll_Vertical_Area_Set			0xA3

//Addressing Setting Command Table
#define OLED_Page_Addressing_Column_Lower_Set	0x00
#define OLED_Page_Addressing_Column_Higher_Set	0x10
#define OLED_Page_Addressing_Page_Start_Set		0xB0
#define OLED_Page_Address_Set					0x22
#define OLED_Memory_Addressing_Set				0x20
#define OLED_Column_Address_Set					0x21

//Hardware Configuration
#define OLED_Display_Start_Line_Set				0x40
#define OLED_Display_Offset_Set					0xD3
#define OLED_Segment_Remap_Set					0xA0
#define OLED_Multiplex_Radio_Set				0xA8
#define OLED_Com_Output_Scan_Inc				0xC0
#define OLED_Com_Output_Scan_Dec				0xC8
#define OLED_Com_Pins_Set						0xDA

//Timing and Driving Scheme Setting Command Table
#define OLED_Display_Clock_Div_Ratio_Set		0xD5
#define OLED_Display_Oscillator_Frequency_Set	0xD5
#define OLED_Precharge_Period_Set				0xD9
#define OLED_VCOMH_Deselect_Level_Set			0xDB
#define OLED_Nop								0xE3

//Charge Pump Command Table
#define OLED_Charge_Pump_Set					0x8D

#define ENDUSUK_CONTRAST						65
#define ENYUKSEK_CONTRAST						255

// I2c port as defined in main generated by CubeMx
#define OLED_I2C_PORT		hi2c1
// I2c address
#define OLED_I2C_ADDR        0x78
// SSD1306 width in pixels
#define OLED_WIDTH           128
// SSD1306 LCD height in pixels
#define OLED_HEIGHT          64

typedef enum {
	Black = 0x00, // Black color, no pixel
	White = 0x01  //Pixel is set. Color depends on LCD
} OLED_COLOR;



//
//  Struct to store transformations
//
typedef struct {
	uint16_t CurrentX;
	uint16_t CurrentY;
	uint8_t Inverted;
	uint8_t Initialized;
} SSD1306_t;

//	Definition of the i2c port in main
extern I2C_HandleTypeDef OLED_I2C_PORT;

//
//  Function definitions
//
uint8_t OLED_Init(void);

void OLED1_Fill(OLED_COLOR color);

void OLED_UpdateScreen(void);

void OLED1_DrawPixel(uint8_t x, uint8_t y, OLED_COLOR color);

char OLED_WriteChar(char ch, FontDef Font, OLED_COLOR color);

char OLED_WriteString(char* str, FontDef Font, OLED_COLOR color);

void OLED_SetCursor(uint8_t x, uint8_t y);

void OLED1_DrawCircle(const uint8_t CenterX, const uint8_t CenterY, const uint8_t Radius, OLED_COLOR color);

void OLED_DrawPixel(uint8_t x, uint8_t y, OLED_COLOR color);

void OLED_ToggleInvert(void);

void OLED_Fill(OLED_COLOR Color);

void OLED_GotoXY(uint16_t x, uint16_t y);

void OLED_DrawLine(uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1, OLED_COLOR c);

void OLED_DrawRectangle(uint16_t x, uint16_t y, uint16_t w, uint16_t h, OLED_COLOR c);

void OLED_DrawFilledRectangle(uint16_t x, uint16_t y, uint16_t w, uint16_t h, OLED_COLOR c);

void OLED_DrawTriangle(uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2, uint16_t x3, uint16_t y3, OLED_COLOR color);

void OLED_DrawFilledTriangle(uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2, uint16_t x3, uint16_t y3, OLED_COLOR color);

void OLED_DrawCircle(int16_t x0, int16_t y0, int16_t r, OLED_COLOR c);

void OLED_DrawFilledCircle(int16_t x0, int16_t y0, int16_t r, OLED_COLOR c);


#endif /* INC_OLEDNEW_H_ */
